export const sampleRoomPlan: RoomPlan = {
  width: 12,
  depth: 10,
  wallHeight: 3,
  furniture: [
    {
      type: 'Bed',
      x: -3,
      z: -3,
      width: 2,
      depth: 3,
      height: 0.6,
      color: '#4A90E2',
    },
    {
      type: 'Nightstand',
      x: -4.5,
      z: -2,
      width: 0.6,
      depth: 0.6,
      height: 0.5,
      color: '#8B4513',
    },
    {
      type: 'Desk',
      x: 3,
      z: -3.5,
      width: 2,
      depth: 1,
      height: 0.75,
      color: '#D2691E',
    },
    {
      type: 'Chair',
      x: 3,
      z: -2,
      width: 0.6,
      depth: 0.6,
      height: 0.9,
      color: '#FF6B6B',
    },
    {
      type: 'Wardrobe',
      x: -4,
      z: 3,
      width: 1.5,
      depth: 0.8,
      height: 2.2,
      color: '#6C5B7B',
    },
    {
      type: 'Bookshelf',
      x: 4,
      z: 3,
      width: 1.2,
      depth: 0.4,
      height: 1.8,
      color: '#C06C84',
    },
    {
      type: 'Coffee Table',
      x: 0,
      z: 1,
      width: 1.5,
      depth: 0.8,
      height: 0.4,
      color: '#F67280',
    },
    {
      type: 'Sofa',
      x: 0,
      z: 3.5,
      width: 2.5,
      depth: 1,
      height: 0.8,
      color: '#355C7D',
    },
    {
      type: 'TV Stand',
      x: 0,
      z: -4,
      width: 2,
      depth: 0.5,
      height: 0.6,
      color: '#2C3E50',
    },
    {
      type: 'Rug',
      x: 0,
      z: 1,
      width: 3,
      depth: 2,
      height: 0.02,
      color: '#E8B4B8',
    },
  ],
};
